### ISSUE TITLE
npm run migrate fails on Windows

### ISSUE THREAD

**Issue by gmarokov** [bradymholt/aspnet-core-react-template#28]
I got Windows 10 running with VS code and `npm run migrate` fails in either terminal Powershell or Git Bash with the following error: 
`$ npm run migrate `

`> cd ./api/ && dotnet ef migrations add $(date +%s) && dotnet ef database update
Specify --help for a list of available options and commands.
Unrecognized command or argument '+%s)'`

I haven't find solution yet.

**Comment by bradymholt** [comment]
@gmarokov can you please try this fix on cp-migration branch? (PR here: https://github.com/bradymholt/aspnet-core-react-template/pull/29)

**Comment by gmarokov** [comment]
@bradymholt working like a charm. Very nice solution, thank you!
