### ISSUE TITLE
Smtp connection refused over ssl

### ISSUE THREAD

**Issue by gmarokov** [bradymholt/aspnet-core-react-template#30]
Hi Brady. I've come accross an issue while tried to register account. I get message that email is sent, but the server responded with error 500 and no email is sent. It looks like it's because the SSL and if I change `client.EnableSsl = false;` instead of true, all works as expected. See screenshot for details. 
![register-account](https://user-images.githubusercontent.com/12663998/38488316-c54a4986-3beb-11e8-9c47-83d041e9f7bd.png)

**Comment by bradymholt** [comment]
What SMTP server are you using?  Is this in the local environment with MailCatcher or a hosted solution?

**Comment by gmarokov** [comment]
It's local enviroment with fresh copy of the template.

**Comment by bradymholt** [comment]
Thanks - fixed here: https://github.com/bradymholt/aspnet-core-react-template/pull/31
