### ISSUE TITLE
Docker composition fails on Fedora 28

### ISSUE THREAD

**Issue by gmarokov** [bradymholt/aspnet-core-react-template#35]
Running `npm start` `docker-compose up` fails to initialize the images.

OS Info: 
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"

Docker info:
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 18.09.0-ce-tp5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc containerd
Default Runtime: containerd
Init Binary: docker-init
containerd version: ce243288e27971e324363de8f322d221635a8521 (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: 1555a78945e56737bc3d15565191d857ee6fa2b9 (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: fec3683
Kernel Version: 4.18.7-200.fc28.x86_64
Operating System: Fedora 28 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.705GiB
Name: localhost.localdomain
ID: GGXK:W7MH:C2QF:T4V4:7SAV:62BL:EAY5:XSUO:QTA7:UYYH:URCU:EYQL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

Docker version: 
Client:
 Version:           18.09.0-ce-beta1
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        78a6bdb
 Built:             Thu Sep  6 22:47:53 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0-ce-tp5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       9eb3d36
  Built:            
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by bradymholt** [comment]
I'm not sure I understand.  You are running `npm start docker-compose up`?  Or, are you saying the `prestart` script (run before `start`) is failing on on `docker-compose`.  In any case, the docker-compose.yml file (https://github.com/bradymholt/aspnet-core-react-template/blob/master/docker-compose.yml) is pretty straightforward so you might try just running `docker-compose up` from root to see if that works.  PRs are welcome.

**Comment by gmarokov** [comment]
I'm running `npm start` which runs `npm prestart` which runs `docker-compose up -d`. When you are saying PRs are welcome, does it mean that you can reproduce it? I've updated the issue forgot to add error log.

**Comment by gmarokov** [comment]
I dropped my containers by running `docker-compose down` then re-created the database with the migrations and everything was fine.
