### ISSUE TITLE
Client test execution is failing

### ISSUE THREAD

**Issue by gmarokov** [bradymholt/aspnet-core-react-template#40]
I'm trying to run `npm test` while api test are passed, client test script can't be started. 
Attaching screenshot of details. 
![npm-test-error](https://user-images.githubusercontent.com/12663998/55116822-4cf55e00-50f1-11e9-8d2d-4d093642bf6e.png)

**Comment by bradymholt** [comment]
I'd welcome a PR to fix this.

**Comment by bradymholt** [comment]
Fixed by d744e42c6d1c1e15c188eb007d41c99490aa8615
