### ISSUE TITLE
Release build template - mvc action not hitting

### ISSUE THREAD

**Issue by mausinc** [bradymholt/aspnet-core-react-template#51]
Hi!
Thanks for an amazing template!
I build this Office 365 add in with your template, i am using several mvc routes for instance to add external accounts which works well in development. When i publish the app to Azure the routes for instance https://afas365-outlook.azurewebsites.net/home/index are not rendered the first time, hard refresh however does.  Locally this works fine
Do you have any thoughts how this can be resolved?
Thanks so much!

To reproduce - Add Mvc project (3.1) with React template in VS 2019. - Add HomeController and Index View - Locally /Home/Index show the MVC View - Release only after hard refresh (https://office365demo.azurewebsites.net/home/index)

**Comment by bradymholt** [comment]
Hi Maurits, thanks for the feedback and I'm glad this template has been useful for you.  I am unable to provide support for any downstream projects.  If you figure out your issue feel free to post back here in case others run into the same thing.  Cheers!

**Comment by mausinc** [comment]
Hi Brady, i understand.

To reproduce 
- Add Mvc project (3.1) with React template in VS 2019. 
- Add HomeController and Index View 
- Locally /Home/Index show the MVC View 
- Release only after hard refresh (https://office365demo.azurewebsites.net/home/index)

**Comment by bradymholt** [comment]
If you figure out a fix, feel free to submit a PR.
