### ISSUE TITLE
Deployment from windows, ansible

### ISSUE THREAD

**Issue by zeiphon** [bradymholt/aspnet-core-react-template#55]
Am I correct in saying that for this setup, deployment to production from a windows machine is not supported? As ansible does not seem to support windows as a 'control machine', at least officially.
I bring this up as the readme mentions `This template was developed and tested on macOS Sierra but should run on Windows as well`.
I suppose it might work with WSL/Windows Subsystem for Linux?

**Comment by bradymholt** [comment]
Docker is only used for the development setup, not deployment or production runtime.  So, as long as you can install and run Docker on Windows you can run this app for local development.

**Comment by zeiphon** [comment]
Sorry am I misunderstanding?

I was talking of ansible, not docker. The task `deploy:prod` uses the `ansible-playbook` command which I'm fairly sure won't be available on windows unless using WSL?

**Comment by bradymholt** [comment]
Oh, I am sorry.  I saw Ansible was was thinking Docker so I goofed that up completely.  You should be able to run this app locally on a Windows machine but if you want to use the production provisioning and deployment scripts in the template, you would need to target a Linux host.  I do believe you can install and use Ansible from Windows and target a Linux host, though.  I committed this to improve clarity here: https://github.com/bradymholt/aspnet-core-react-template/commit/ba810e65cb73279113c25dfa7a74b6e6df74d235
